export const AUTH_LOADING_START = "AUTH_LOADING_START";
export const AUTH_LOADING_END_FAILURE = "AUTH_LOADING_END_FAILURE";
export const AUTH_LOADING_END_SUCCESS = "AUTH_LOADING_END_SUCCESS";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
